apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy13
  labels:
    app: autodeploy13
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718200863316
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy13
  template:
    metadata:
      labels:
        app: autodeploy13
    spec:
      containers:
        - name: autodeploy13
          image: acrworkflow1718200863316.azurecr.io/image-workflow-1718200863316:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
